### ISSUE TITLE
Test installation documentation and processes

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan-tools#146] opened 2019-10-22 14:56 UTC
## QA Steps

- [ ] Read through https://github.com/GetDKAN/dkan-tools/tree/update-readme-04-22 to create your own fresh build of dkan2 with dkan-tools
- [ ] Read through ~~https://docs.getdkan.com~~ (https://github.com/GetDKAN/dkan/pull/3052)
- [ ] Document any errors, confusing bits, typos, etc. in this ticket

**Comment by erogray** [comment] 2019-11-25 21:34
@beeyayjay 
https://dkan.readthedocs.io/en/latest/ has DKAN classic documentation
https://getdkan.github.io/dkan2/ has DKAN 2 documentation

can you post notes here?

**Comment by beeyayjay** [comment] 2019-11-26 22:02
## Testing DKAN 2 Install process

- dkan-tools didn't complain that my version of Drush is out-of-date. (The doc said it most likely would.) In fact, composer installed it during the `dktl make --frontend` process, so maybe the doc is out of date?

- A message from `dktl make --frontend` said:
`you will need to enable the dkan_frontend module . Do this by running "dktl install" with the "--frontend" option as well, or else run "drush en dkan_frontend" after installation.` No mention of this in the doc.

- Running `dktl drush uli --uri=dkan` returned `http://dkan/user/reset/1/1574796236/KrIlmrb231iEMdSWTMi5R8d4G412uPXTZdIAnOgfUf4/login` which took me to `http://www.dkan.com/user/reset/1/1574796236/KrIlmrb231iEMdSWTMi5R8d4G412uPXTZdIAnOgfUf4/login`, which appears to be a 404 page.
I was already running docker before I started this. Could that be why I ran into this?

- Went to the site, using my normal docker host name. The uli login worked when I substituted that host, but the theme was a mess (zero styling). Enabled `dkan_frontend`, but that didn't help. Finally went back to the doc, and realized I should have read the "Graphical User Interface (GUI)" section.

- Struggled for a while with how to locate `data-catalog-frontend`. Finally clicked on " React App's" link above and found it linked to a repo with that name.

- Tried to put `data-catalog-frontend` in docroot, but there was already a symbolic link of that name to `/var/www/src/frontend`. Since the contents of src/frontend looked the same as the `data-catalog-frontend` repo, I tried following the readme file there.

### Installing data-catalog-frontend
- Had to use `sudo` to install gatsby-cli globally (no big deal).
- Steps 3 & 4 (clone repository and `cd data-catalog-frontend`) were a little confusing since I was already in `src/frontend`.
- Decided that `instead of runnig the development server at the end, build a copy with npm run build` in the main docs meant skip `5. Run the server: ...` in the data-catalog-frontend readme.
- Ran `npm run build`. It failed with
```
 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

getaddrinfo ENOTFOUND dkan dkan:80
```
Maybe related to my earlier problem with `dktl drush uli --uri=dkan`.

## DKAN 2 installation doc typos

- "DKAN for Drupal 8 is trying to work with independent pieces that can be used **no** only by us but any other open data catalog.""

- "Place the source for the data-catalog-frontend **in side** of your docroot directory."

- "instead of **runnig** the development server at the end"

**Comment by janette** [comment] 2020-01-14 06:39
I'm getting an error on the bower-asset symlink

![test-install](https://user-images.githubusercontent.com/314172/72272186-d6790c80-35ed-11ea-8164-d1f43be2e6dc.png)

The problem is it requires a token

```
Installing bower-asset/json-forms (v1.6.3): Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+cli+2020-01-14+0355
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
```

**Comment by janette** [comment] 2020-01-14 14:57
and another error:
```
[ERROR] Could not link /var/www/src/schema. Folders /var/www/src/schema and 'docroot' must both be present to create   
         link.
```

**Comment by kimwdavidson** [comment] 2020-01-30 17:25
Janette to add QA instructions and assign to a reviewer

**Comment by thejuliekramer** [comment] 2020-04-27 15:49
I originally was getting an error ```[ERROR] Unable to add Drush and Dkan2 dependencies.``` when running ```dktl make``` I restarted my computer and this was fixed - I think this was due to my docker not being updated because previously my docker containers were not started by this command.

```dktl make```  brought up these warnings

```
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package getdkan/dkan2 is abandoned, you should avoid using it. Use getdkan/dkan instead.

Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package getdkan/dkan2 is abandoned, you should avoid using it. Use getdkan/dkan instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
```

and

```
 [WARNING] Skipping linking /var/www/src/schema. Folders /var/www/src/schema and 'docroot' must both be present to
           create link.
```

`dktl install --demo` worked but had this warning: 

```
sh: 1: frontend:install: not found
 [Exec]  Exit code 127  Time 0.006s
 [Exec] Running frontend:build in /var/www/docroot
sh: 1: frontend:build: not found
 [Exec]  Exit code 127  Time 0.003s
```

**Comment by thejuliekramer** [comment] 2020-04-27 16:02
I am reading through this page https://getdkan.github.io/dkan2/dev-maintain.html

Additional modules, themes, or libraries, or newer versions of ones already present in `modules/contrib/dkan`, can be placed in `modules/custom`, `themes/custom`, or `libraries/custom`.

I am not sure what "of ones" means here? custom code?

**Comment by thejuliekramer** [comment] 2020-05-04 19:23
On Step 6 of [DKAN tools installation](https://github.com/GetDKAN/dkan-tools/) the command gives me a local url but I get an error when trying to access it 

<img width="624" alt="Screen Shot 2020-05-04 at 2 22 19 PM" src="https://user-images.githubusercontent.com/7378770/81004970-dad26b00-8e12-11ea-96dc-f3c961887159.png">

**Comment by thejuliekramer** [comment] 2020-05-04 20:10
Running the make command more than once results in an error of not being able to delete this file 
`Could not delete /var/www/docroot/sites/default/default.services.yml`
dktl dc exec cli chmod +w /var/www/src/site fixes this error and allows you to run make again

**Comment by thejuliekramer** [comment] 2020-05-04 20:51
`http://localtest.me:32772/` now returns this page 
<img width="1680" alt="Screen Shot 2020-05-04 at 3 50 43 PM" src="https://user-images.githubusercontent.com/7378770/81012369-0c513380-8e1f-11ea-893d-d24b30c47503.png">

Maybe it would be better to redirect to a login page so it doesn't look like an error?

**Comment by thejuliekramer** [comment] 2020-05-06 20:44
Should I be able to use the `composer` and `drush` commands with just the installation documented in the DKAN tools readme? It seems like no but [this bit](https://github.com/GetDKAN/dkan/blob/405-docs-revamp/docs_assets/pages/overview_installation.md#installing-dkan) makes me think I should be able to

**Comment by thtas** [comment] 2020-05-27 07:21
I’ve been evaluating DKAN2 as we’re starting to look at moving some old DKAN sites forward to using it. Keeping in mind i’m completely new to decoupled sites and React and Gatsby.

These are some notes/gotchas i found while evaluating it after getting things running in a basic way following the documentation. Perhaps it could lead to some improvements to the docs or help other new users a bit.

1. If you want to create datasets from the UI, you need to enable the React based form. this must be done with `dktl install --demo` as It’s not available with the regular install. This would be nice to fix.
2. After creating a dataset, you will get a 404 error when you try and visit it unless you run `dktl frontend:build`. I thought this would be done automatically, but perhaps I missed a step somewhere.
3. If your new dataset contains an organisation named something which is not in `src/frontend/src/assets/publishers.json` the npm/Gatsby build task will fail and the link to the dataset will produce an error. The npm build error is 
```
failed Building static HTML for pages - 7.436s

 ERROR #95313 

Building static HTML failed for path "/dataset/95c2fbab-f44c-4c25-853f-29735d6371e1"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  WebpackError: TypeError: Cannot read property 'imageUrl' of undefined
  
  - build-html.js:110 doBuildPages
    [frontend]/[gatsby]/dist/commands/build-html.js:110:24
  
  - build-html.js:124 async buildHTML
    [frontend]/[gatsby]/dist/commands/build-html.js:124:3
  
  - build.js:200 async build
    [frontend]/[gatsby]/dist/commands/build.js:200:5
```

I believe this error stems from src/frontend/src/services/datastore.js. To fix this, you must rename the organisation in the test dataset or add a new organisation to the src/frontend/src/assets/publishers.json file. i believe it has to match exactly.

4. Datasets require at least one "distribution" or you will get a white screen and a client-side error when visiting the page after build. This is fine, but it would be handy if it was highlighted.

5. I’m still figuring out how to add data. It looks like there are some brush commands for this. It would be great if this could also be done using the UI and I assume this something that will be worked on.

@thejuliekramer you can run `dktl drush status` or other drush command like that.

**Comment by janette** [comment] 2020-05-27 18:30
@thtas Hi, thanks for testing this new version

1. The `metastore_form` module provides the dataset form UI and is a separate application from the frontend so you do not need the data-catalog-frontend to add or edit the datasets.
2. Yes, currently the frontend needs to be rebuilt after adding new datasets. We plan to move off of Gatsby so this will not be required in the future.
3. Fix for this in in review https://github.com/GetDKAN/data-catalog-frontend/pull/40
4. Will investigate, you should not need a distribution.
5. Harvest and API are the other non-UI methods for adding data. You will need the **API user** role to use the API commands other than `GET` see https://demo.getdkan.com/modules/contrib/dkan/docs/datasetapi.html

**Comment by janette** [comment] 2020-06-04 20:14
doc updates will continue based on new issues, this one has served its purpose, closing

**Closed by janette** 2020-06-04 20:14 UTC
