### ISSUE TITLE
Document testing options for Behat in projects

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#41] opened 2018-09-11 15:09 UTC
The standard procedure for running tests in DKAN implementation projects ("clients") will be to run only tests that have a `@smoketest` tag (as opposed to running the full suite on PRs against DKAN repo). 

Document how to set this up in a new project in the README using circle config. Also document other use-cases of filtering tests.

**Comment by janette** [comment] 2018-09-21 14:41
Reminder that client sites have behat.custom.yml files to make adjustments to the region mapping and field titles https://github.com/NuCivic/healthdata/blob/master/config/tests/behat.custom.yml#L18

**Comment by kimwdavidson** [comment] 2019-03-22 15:21
Duplicate of #40. Closing

**Closed by kimwdavidson** 2019-03-22 15:21 UTC
Labels: To Do
